config/routes.rb
Rails.application.routes.draw do
  resources :suppliers
  resources :products
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#index"
end

app/models/supplier.rb
class Supplier < ApplicationRecord

  validates_presence_of :name, :primary_category, :secondary_category

end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  # GET /suppliers
  # GET /suppliers.json
  def index
    @suppliers = Supplier.all.paginate(page: params[:page])
  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new

    @filterrific = initialize_filterrific(
      Product,
      params[:filterrific],
      :select_options => {
        sorted_by: Product.options_for_sorted_by,
        with_parent: MarketplaceCategory.options_for_select,
        with_child: MarketplaceCategory.options_for_select_children_from_name(params[:filterrific]),
      }
    ) or return
    respond_to do |format|
      format.html
      format.js
    end
    
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)
    @primary_category = MarketplaceCategory.find_by_name(@supplier.primary_category) if @supplier.primary_category.present?
    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1
  # PATCH/PUT /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: 'Supplier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:name, :primary_category, :secondary_category)
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_child_categories_dropdown.html.erb
<%= select_tag "supplier[marketplace_category_id]", options_for_select(child_categories, @child_category_id), class: "form-control", include_blank: '- Any -' %>

app/views/suppliers/_form.html.erb
<%= form_with(model: supplier, local: true) do |form| %>
  <% if supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>
      <ul>
        <% supplier.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <div class="col-md-2">
      <%= form.label :name %>
    </div>
    <div class="col-md-6">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-2">
      <%= form.label :primary_category %>
    </div>
    <div class="col-md-6">
      <%= form.select :primary_category, MarketplaceCategory.roots.map{|mp| [mp.name, mp.name]}, {include_blank: '- Any -'}, class: "form-control", id: "supplier_primary_category" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-2">
      <%= form.label :secondary_category %>
    </div>
    <div class="col-md-6" id="child_categories_dropdown">
      <% if @primary_category.present? %>
        <%= form.select :secondary_category, @primary_category.children.map{|mp| [mp.name, mp.name]}, {include_blank: '- Any -'}, class: "form-control" %>
      <% else %>
        <%= form.select :secondary_category, [], {include_blank: '- Any -'}, class: "form-control" %>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-2">
    </div>
    <div class="col-md-6">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>

  <div class="actions">
  </div>
<% end %>

<script type="text/javascript">
  $("#supplier_primary_category").change(function(){
    var primary_category = encodeURIComponent($(this).val());
    $.getJSON("/suppliers/new.js?filterrific[with_parent]="+primary_category+"&callback=?"); 
  })
</script>

app/views/suppliers/edit.html.erb
<div class="jumbotron">
  <h1>Edit Supplier</h1>
  <div class="float-right">
    <%= link_to 'Show', @supplier, class: "btn btn-info" %>
    <%= link_to 'Back', suppliers_path, class: "btn btn-info" %>
  </div>
</div>
<%= render 'form', supplier: @supplier %>

app/views/suppliers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
  <h1>Suppliers</h1>
  <div class="float-right">
    <%= link_to 'New Supplier', new_supplier_path, class: "btn btn-info" %>
  </div>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Primary category</th>
      <th>Secondary category</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= supplier.name %></td>
        <td><%= supplier.primary_category %></td>
        <td><%= supplier.secondary_category %></td>
        <td>
          <%= link_to 'Show', supplier %> | 
          <%= link_to 'Edit', edit_supplier_path(supplier) %> | 
          <%= link_to 'Destroy', supplier, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @suppliers %>
  </div>
  <%= will_paginate @suppliers, container: false %>
</div>

app/views/suppliers/new.html.erb
<div class="jumbotron">
  <h1>New Supplier</h1>
  <div class="float-right">
    <%= link_to 'Back', suppliers_path, class: "btn btn-info" %>
  </div>
</div>
<%= render 'form', supplier: @supplier %>

app/views/suppliers/new.js.erb
$("#child_categories_dropdown").html("<%= escape_javascript(render(partial: 'suppliers/child_categories_dropdown', locals: {child_categories: @filterrific.select_options[:with_child]})) %>");

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
  <h1>Supplier - <%= @supplier.name %></h1>
  <div class="float-right">
    <%= link_to 'Edit', edit_supplier_path(@supplier), class: "btn btn-info" %>
    <%= link_to 'Back', suppliers_path, class: "btn btn-info" %>
  </div>
</div>
<table class="table">
  <tbody>
    <tr>
      <td><strong>Name:</strong></td>
      <td><%= @supplier.name %></td>
    </tr>
    <tr>
      <td><strong>Primary Category:</strong></td>
      <td><%= @supplier.primary_category %></td>
    </tr>
    <tr>
      <td><strong>Secondary Category:</strong></td>
      <td><%= @supplier.secondary_category %></td>
    </tr>
  </tbody>
</table>